@startuml
set separator none
title Catalog

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("DddLibraryApplication.DddLibraryApplication_boundary", "DddLibraryApplication", $tags="") {
  Component(DddLibraryApplication.DddLibraryApplication.Catalog, "Catalog", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml